on: [push]
jobs:
  callCKBAPI:
    runs-on: ubuntu-latest
    steps:
    - name: Call CKB API
      uses: dkershner6/post-api-call-action@v2
      with:
        url: https://ckbapplicationserver.onrender.com/demo/push
        data: "{\"command\": \"publish\"}"
        headers: "{\"Authorization\": \"Bearer ${{ secrets.API_KEY }}\"}"
